log:
  level: INFO
  include_timestamp: true

data:
  input_path: data/penguins_size.csv
  test_size: 0.2
  validation_size: 0.2
  random_state: 42

model:
  model_type: lightgbm
  hyperparameters:
    objective: multiclass
    num_class: 3
    metric: multi_logloss
    boosting_type: gbdt
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9

mlflow:
  tracking_uri: duckdb+artifact:///mlflow-artifacts/mlruns.duckdb
  experiment_name: penguin-classification
  register_model: true
  log_artifacts: true

output_dir: output