name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint with ruff
        run: |
          uvx ruff check .

      - name: Check formatting with ruff
        run: |
          uvx ruff format . --check

      - name: Type check with ty
        run: |
          uvx ty check .

      - name: Test with pytest
        run: |
          uv run pytest tests
